package com.ecliptia.oikos.ui.theme

import androidx.compose.ui.graphics.Color

// Generated by Material Theme Builder
// Source color: #4CAF50 (Green)

val PrimaryLight = Color(0xFF006E21)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9EF699)
val OnPrimaryContainerLight = Color(0xFF002205)

val SecondaryLight = Color(0xFF52634F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD5E8CF)
val OnSecondaryContainerLight = Color(0xFF101F10)

val TertiaryLight = Color(0xFF38656A)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFBCEBEF)
val OnTertiaryContainerLight = Color(0xFF002022)

val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val BackgroundLight = Color(0xFFF7FBF2)
val OnBackgroundLight = Color(0xFF191C18)
val SurfaceLight = Color(0xFFF7FBF2)
val OnSurfaceLight = Color(0xFF191C18)
val SurfaceVariantLight = Color(0xFFDEE5D9)
val OnSurfaceVariantLight = Color(0xFF424940)
val OutlineLight = Color(0xFF72796F)


val PrimaryDark = Color(0xFF83D980)
val OnPrimaryDark = Color(0xFF00390D)
val PrimaryContainerDark = Color(0xFF005316)
val OnPrimaryContainerDark = Color(0xFF9EF699)

val SecondaryDark = Color(0xFFB9CCB4)
val OnSecondaryDark = Color(0xFF253423)
val SecondaryContainerDark = Color(0xFF3B4B39)
val OnSecondaryContainerDark = Color(0xFFD5E8CF)

val TertiaryDark = Color(0xFFA0CFD3)
val OnTertiaryDark = Color(0xFF00373A)
val TertiaryContainerDark = Color(0xFF1F4E52)
val OnTertiaryContainerDark = Color(0xFFBCEBEF)

val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val BackgroundDark = Color(0xFF191C18)
val OnBackgroundDark = Color(0xFFE2E3DE)
val SurfaceDark = Color(0xFF191C18)
val OnSurfaceDark = Color(0xFFE2E3DE)
val SurfaceVariantDark = Color(0xFF424940)
val OnSurfaceVariantDark = Color(0xFFC2C9BE)
val OutlineDark = Color(0xFF8C9388)

// --- Gold (Excellent) Theme ---
val GoldLight = Color(0xFFB78C00)
val OnGoldLight = Color(0xFFFFFFFF)
val GoldLightContainer = Color(0xFFFFE082)
val OnGoldLightContainer = Color(0xFF3D2C00)

val GoldDark = Color(0xFFFFD600)
val OnGoldDark = Color(0xFF4F3700)
val GoldDarkContainer = Color(0xFF705000)
val OnGoldDarkContainer = Color(0xFFFFE082)

// --- Orange (Warning) Theme ---
val OrangeLight = Color(0xFFFF9800)
val OnOrangeLight = Color(0xFFFFFFFF)
val OrangeLightContainer = Color(0xFFFFCC80)
val OnOrangeLightContainer = Color(0xFF4F2D00)

val OrangeDark = Color(0xFFFFB74D)
val OnOrangeDark = Color(0xFF4F2D00)
val OrangeDarkContainer = Color(0xFF704200)
val OnOrangeDarkContainer = Color(0xFFFFCC80)